openapi: 3.0.3
info:
  version: 1.0.0
  title: Pakkasmarja ERP services

security:
  - bearerAuth: []

paths:
  /v1/system/ping:
    get:
      operationId: ping
      summary: Replies with pong
      description: Replies ping with pong
      tags:
        - System
      responses:
        "200":
          description: Pong
          content:
            text/plain:
              schema:
                type: string

  /v1/contracts:
    get:
      operationId: listContracts
      summary: Lists contracts
      description: Lists contracts
      tags:
        - Contracts
      parameters:
        - name: startDate
          in: query
          description: Filter results by start date
          schema:
            type: string
            format: date
        - name: businessPartnerCode
          in: query
          description: Filter results by business partner code
          schema:
            type: string
        - name: contractStatus
          in: query
          description: Filter results by contract status
          schema:
            $ref: "#/components/schemas/SapContractStatus"
      responses:
        "200":
          description: Contract
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SapContract"
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      operationId: createContract
      summary: Create a contract.
      description: Creates a new contract.
      tags:
        - Contracts
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SapContract"
        description: Payload
        required: true
      responses:
        "200":
          description: Created contract
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SapContract"
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  "/v1/contracts/{sapId}":
    get:
      operationId: findContract
      summary: Find a contract.
      description: Finds a contract by id.
      tags:
        - Contracts
      parameters:
        - name: sapId
          required: true
          in: path
          description: sap contract id
          schema:
            type: string
            pattern: /^[0-9]{4}-[0-9]{4}-[0-9]{3}$/
            description: ID in format of "[year]-[SAP contract document number]-[item group ID]"
      responses:
        "200":
          description: Contract
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SapContract"
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/items:
    get:
      operationId: listItems
      summary: List items.
      description: Lists items.
      tags:
        - Items
      parameters:
        - name: itemGroupCode
          in: query
          description: Filter results by item group code
          schema:
            type: integer
            format: int32
        - name: updatedAfter
          in: query
          description: Filter results by updated after given date time
          schema:
            type: string
            format: date-time
        - name: firstResult
          in: query
          description: First result. Defaults to 0
          schema:
            type: integer
        - name: maxResults
          in: query
          description: Max results. Defaults to 10
          schema:
            type: integer
      responses:
        "200":
          description: List of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SapItem"
          headers:
            X-Total-Count:
              schema:
                type: integer
                format: int64
              description: Total count of items with given filters.
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  "/v1/items/{sapId}":
    get:
      operationId: findItem
      summary: Find a item.
      description: Finds a item by id.
      tags:
        - Items
      parameters:
        - name: sapId
          required: true
          in: path
          description: sap item id
          schema:
            type: integer
            format: int32
            description: Item code in SAP
      responses:
        "200":
          description: Item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SapItem"
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/businessPartners:
    get:
      operationId: listBusinessPartners
      summary: List businessPartners.
      description: Lists businessPartners.
      tags:
        - BusinessPartners
      parameters:
        - name: updatedAfter
          in: query
          description: Filter results by updated after given date time
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: List of businessPartners
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SapBusinessPartner"
          headers:
            X-Total-Count:
              schema:
                type: integer
                format: int64
              description: Total count of businessPartners with given filters.
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      description: Error object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    SapContract:
      type: object
      description: SapContract object
      required:
        - id
        - businessPartnerCode
        - contactPersonCode
        - itemGroupCode
        - status
      properties:
        id:
          type: string
          pattern: /^[0-9]{4}-[0-9]{4}-[0-9]{3}$/
          description: ID in format of "[year]-[SAP contract document number]-[item group ID]"
        businessPartnerCode:
          type: integer
          format: int32
          description: SAP business partner code
        contactPersonCode:
          type: integer
          format: int32
          description: SAP contact person code
        itemGroupCode:
          type: integer
          format: int32
          description: SAP item group code. This field must match with the ID postfix
        deliveredQuantity:
          type: number
          format: double
          readOnly: true
        startDate:
          type: string
          format: date
          readOnly: true
        endDate:
          type: string
          format: date
          readOnly: true
        signingDate:
          type: string
          format: date
          readOnly: true
        terminateDate:
          type: string
          format: date
          readOnly: true
        remarks:
          type: string
        status:
          $ref: "#/components/schemas/SapContractStatus"

    SapContractStatus:
      type: string
      enum:
        - APPROVED
        - ON_HOLD
        - DRAFT
        - TERMINATED

    SapItem:
      type: object
      description: Sap item
      required:
        - code
        - name
        - salesUnit
        - purchaseUnit
      properties:
        code:
          type: integer
          format: int32
          description: SAP item code.
          readOnly: true
        itemGroupCode:
          type: integer
          format: int32
          description: SAP item group code.
          readOnly: true
        name:
          type: string
          readOnly: true
        purchaseUnit:
          type: string
          readOnly: true
        batchManaged:
          type: boolean
          readOnly: true
        updated:
          type: string
          format: date-time
          readOnly: true

    SapBusinessPartner:
      type: object
      description: Sap item
      required:
        - code
        - email
      properties:
        code:
          type: integer
          format: int32
          description: SAP business partner code.
          readOnly: true
        email:
          type: string
          format: email
        phoneNumbers:
          type: array
          readOnly: true
          items:
            type: string
        addresses:
          type: array
          readOnly: true
          items:
            $ref: "#/components/schemas/SapAddress"
        companyName:
          type: string
          readOnly: true
        federalTaxId:
          type: string
          readOnly: true
        vatLiable:
          type: string
          readOnly: true
          enum:
            - NOT_LIABLE
            - FI
            - EU
        bankAccounts:
          type: array
          readOnly: true
          items:
            $ref: "#/components/schemas/SapBankAccount"
        updated:
          type: string
          format: date-time
          readOnly: true

    SapAddress:
      type: object
      properties:
        name:
          type: string
        type:
          $ref: "#/components/schemas/SapAddressType"
        streetAddress:
          type: string
        postalCode:
          type: string
        city:
          type: string

    SapBankAccount:
      type: object
      properties:
        BIC:
          type: string
        IBAN:
          type: string

    SapAddressType:
      type: string
      enum:
        - BILLING
        - DELIVERY